CREATE OR REPLACE PACKAGE PA_PERSONAS AS
/**************************************************************************************
   NAME:       PA_PERSONAS 

     Ver        Date                  Author                           Description
  ---------  ----------     ---------------------------          -----------------------
    1.0      2026-02-19      Alejandro Jimenez           1. 
****************************************************************************************/


  PROCEDURE SP_INSERT (
    PA_APELLIDOPATERNO     IN TA_PERSONAS.APELLIDOPATERNO%TYPE,
    PA_APELLIDOMATERNO     IN TA_PERSONAS.APELLIDOMATERNO%TYPE,
    PA_NOMBRES             IN TA_PERSONAS.NOMBRES%TYPE,
    PA_FECHANACIMIENTO     IN TA_PERSONAS.FECHANACIMIENTO%TYPE,
    PA_RFC                 IN TA_PERSONAS.RFC%TYPE,
    PA_DIRECCION           IN TA_PERSONAS.DIRECCION%TYPE,
    PA_COLONIAPOBLACION    IN TA_PERSONAS.COLONIAPOBLACION%TYPE,
    PA_DELEGACIONMUNICIPIO IN TA_PERSONAS.DELEGACIONMUNICIPIO%TYPE,
    PA_CIUDAD              IN TA_PERSONAS.CIUDAD%TYPE,
    PA_ESTADO              IN TA_PERSONAS.ESTADO%TYPE,
    PA_CP                  IN TA_PERSONAS.CP%TYPE,
    PA_FDREGISTRO          IN TA_PERSONAS.FDREGISTRO%TYPE,
    PA_USUARIO_MODIFICO    IN TA_PERSONAS.USUARIO_MODIFICO%TYPE,
    PA_CODE               OUT NUMBER,
    PA_MSG                OUT VARCHAR2
  );

END PA_PERSONAS;
/


CREATE OR REPLACE PACKAGE BODY PA_PERSONAS AS

  PROCEDURE SP_INSERT (
    PA_APELLIDOPATERNO     IN TA_PERSONAS.APELLIDOPATERNO%TYPE,
    PA_APELLIDOMATERNO     IN TA_PERSONAS.APELLIDOMATERNO%TYPE,
    PA_NOMBRES             IN TA_PERSONAS.NOMBRES%TYPE,
    PA_FECHANACIMIENTO     IN TA_PERSONAS.FECHANACIMIENTO%TYPE,
    PA_RFC                 IN TA_PERSONAS.RFC%TYPE,
    PA_DIRECCION           IN TA_PERSONAS.DIRECCION%TYPE,
    PA_COLONIAPOBLACION    IN TA_PERSONAS.COLONIAPOBLACION%TYPE,
    PA_DELEGACIONMUNICIPIO IN TA_PERSONAS.DELEGACIONMUNICIPIO%TYPE,
    PA_CIUDAD              IN TA_PERSONAS.CIUDAD%TYPE,
    PA_ESTADO              IN TA_PERSONAS.ESTADO%TYPE,
    PA_CP                  IN TA_PERSONAS.CP%TYPE,
    PA_FDREGISTRO          IN TA_PERSONAS.FDREGISTRO%TYPE,
    PA_USUARIO_MODIFICO    IN TA_PERSONAS.USUARIO_MODIFICO%TYPE,
    PA_CODE               OUT NUMBER,
    PA_MSG                OUT VARCHAR2
  ) IS
    VL_IDPERSONA NUMBER(38,0);
    VL_UNO          NUMBER(38,0) := 1;
    VL_CERO         NUMBER(38,0) := 0;
    VL_USUARIO      VARCHAR2(50);
    VL_DATE         DATE;
  BEGIN
    VL_DATE    := SYSDATE;
    VL_USUARIO := 'AJG';
    VL_IDPERSONA := SEQ_TA_PERSONAS.NEXTVAL;

    INSERT INTO TA_PERSONAS (
      ID_PERSONA,
      APELLIDOPATERNO, 
      APELLIDOMATERNO, 
      NOMBRES,
      FECHANACIMIENTO, 
      RFC, 
      DIRECCION, 
      COLONIAPOBLACION,
      DELEGACIONMUNICIPIO, 
      CIUDAD, 
      ESTADO, 
      CP,
      FDREGISTRO,
      USUARIO_MODIFICO
    )
    VALUES (
      VL_IDPERSONA,
      PA_APELLIDOPATERNO, 
      PA_APELLIDOMATERNO, 
      PA_NOMBRES,
      PA_FECHANACIMIENTO, 
      PA_RFC, 
      PA_DIRECCION, 
      PA_COLONIAPOBLACION,
      PA_DELEGACIONMUNICIPIO, 
      PA_CIUDAD, 
      PA_ESTADO, 
      PA_CP,
      VL_DATE,
      VL_USUARIO
    );
    COMMIT;
      PA_CODE := VL_UNO;
      PA_MSG  := 'INSERCION EXITOSA EN LA TA_PERSONAS';
  EXCEPTION
      WHEN OTHERS THEN
            ROLLBACK;
            PA_CODE := VL_CERO;
            PA_MSG  := 'ERROR AL INSERTAR EN LA TA_PERSONAS';
    END SP_INSERT;

END PA_PERSONAS;
/
