SET SERVEROUTPUT ON;
DECLARE
  PA_APELLIDOPATERNO VARCHAR2(30);
  PA_APELLIDOMATERNO VARCHAR2(30);
  PA_NOMBRES VARCHAR2(30);
  PA_FECHANACIMIENTO DATE;
  PA_RFC VARCHAR2(30);
  PA_DIRECCION VARCHAR2(30);
  PA_COLONIAPOBLACION VARCHAR2(30);
  PA_DELEGACIONMUNICIPIO VARCHAR2(30);
  PA_CIUDAD VARCHAR2(30);
  PA_ESTADO VARCHAR2(30);
  PA_CP NUMBER;
  PA_FDREGISTRO DATE;
  PA_USUARIO_MODIFICO VARCHAR2(30);
  PA_CODE NUMBER;
  PA_MSG VARCHAR2(200);
BEGIN
  PA_APELLIDOPATERNO := 'Jimenez';
  PA_APELLIDOMATERNO := 'Garcia';
  PA_NOMBRES := 'Alejandro';
  PA_FECHANACIMIENTO := TO_DATE('15/05/1990','DD/MM/YYYY');
  PA_RFC := 'JGA99087577HVJ';
  PA_DIRECCION := 'AV INDEPENDENCIA';
  PA_COLONIAPOBLACION := 'LAS FLORES';
  PA_DELEGACIONMUNICIPIO := 'TEHUACAN';
  PA_CIUDAD := 'TEHUACAN';
  PA_ESTADO := 'PUEBLA';
  PA_CP := '75786';
  PA_FDREGISTRO := SYSDATE;
  PA_USUARIO_MODIFICO := 'AJG';

  PA_PERSONAS.SP_INSERT(
    PA_APELLIDOPATERNO => PA_APELLIDOPATERNO,
    PA_APELLIDOMATERNO => PA_APELLIDOMATERNO,
    PA_NOMBRES => PA_NOMBRES,
    PA_FECHANACIMIENTO => PA_FECHANACIMIENTO,
    PA_RFC => PA_RFC,
    PA_DIRECCION => PA_DIRECCION,
    PA_COLONIAPOBLACION => PA_COLONIAPOBLACION,
    PA_DELEGACIONMUNICIPIO => PA_DELEGACIONMUNICIPIO,
    PA_CIUDAD => PA_CIUDAD,
    PA_ESTADO => PA_ESTADO,
    PA_CP => PA_CP,
    PA_FDREGISTRO => PA_FDREGISTRO,
    PA_USUARIO_MODIFICO => PA_USUARIO_MODIFICO,
    PA_CODE => PA_CODE,
    PA_MSG => PA_MSG
  );

DBMS_OUTPUT.PUT_LINE('PA_CODE = ' || PA_CODE);

DBMS_OUTPUT.PUT_LINE('PA_MSG = ' || PA_MSG);
 
END;
