CREATE TABLE TA_PERSONAS (
    ID_PERSONA          NUMBER(38,0) NOT NULL,
    APELLIDOPATERNO     VARCHAR2(30) NOT NULL,
    APELLIDOMATERNO     VARCHAR2(30) NOT NULL,
    NOMBRES             VARCHAR2(30) NOT NULL,
    FECHANACIMIENTO     DATE         NOT NULL,
    RFC                 VARCHAR2(30) NOT NULL,
    DIRECCION           VARCHAR2(30) NOT NULL,
    COLONIAPOBLACION    VARCHAR2(30) NOT NULL,
    DELEGACIONMUNICIPIO VARCHAR2(30) NOT NULL,
    CIUDAD              VARCHAR2(30) NOT NULL,
    ESTADO              VARCHAR2(30) NOT NULL,
    CP                  NUMBER(38,0) NOT NULL,
    FDREGISTRO          DATE         NOT NULL,
    USUARIO_MODIFICO    VARCHAR2(30) NOT NULL
);


ALTER TABLE TA_PERSONAS ADD (
    CONSTRAINT TA_PERSONAS PRIMARY KEY ( ID_PERSONA )
);